app/urls.py
from django.urls import path
from . import views
# from django.conf.urls import include
from django.urls import path, include
from django_email_verification import urls as email_urls

urlpatterns = [
    path('', views.index, name='index'),
    path('inner-page/', views.inner_page, name='inner-page'),
    path('index-login/', views.index_login, name='index-login'),
    path('index-dr/', views.index_dr, name='index-dr'),
    path('sample/', views.sample, name='sample'),
    path('login/', views.userLogin, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('screening/', views.screening, name='screening'),
    path('screening-dr/', views.screening_dr, name='screening-dr'),
    path('screening-data/', views.screening_data, name='screening-data'),
    path('appointment-data/', views.appointment_data, name='appointment-data'),
    path('screening-questions/', views.screening_questions, name='screening-questions'),
    path('screening-qn-2/', views.screening_qn_2, name='screening-qn-2'),
    path('about-us/', views.about_us, name='about-us'),
    path('profile-details/', views.profile_details, name='profile-details'),
    path('wait/', views.wait, name='wait'),
    path('result/', views.result, name='result'),
    path('appointment/', views.appointment, name='appointment'),
    path('confirmemail/', views.confirmemail, name="confirmemail"),
    path('doctor-details/', views.doctor_details, name="doctor-details"),
    path('index-intern/', views.index_intern, name="index-intern"),
    path('screening-intern/', views.screening_intern, name="screening-intern"),
    path('trackappointment/', views.trackappointment, name="trackappointment"),
    path('screening-data-intern/', views.screening_data_intern, name="screening-data-intern"),
    path('generate-report/', views.generate_report, name="generate-report"),
    path('generate-report-pk/<int:pk>/', views.generate, name="generate-report-pk"),
    path('reschedule', views.reschedule, name="reschedule"),
    path('depression-questions', views.depression_questions, name="depression-questions"),
    path('verifyotppage', views.verifyotppage, name="verifyotppage"),
    path('verifyotp', views.verifyotp, name="verifyotp"),
    # path("blog/", include(("blog.urls", "blog"), namespace = "blog")),
]

blog/urls.py
from django import views
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.StartingPageView.as_view(), name='starting-page'),
    path('posts', views.AllPostsView.as_view(), name='posts-page'),
    path('posts/<int:pk>', views.SinglePostView.as_view(), name='post-detail-page'), #/posts/my-first-post
    path('create-post', views.CreateBlogPost, name='create-post'),
    # path('read-later', views.ReadLaterView.as_view(), name='read-later'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("blog/", include(("blog.urls", "blog"), namespace = "blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "project.views.page_not_found_view"

blog/models.py
from django.utils import timezone
from distutils.command.upload import upload
from select import select
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Tag(models.Model):
    caption = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.caption}"

class Post(models.Model):
    title = models.CharField(max_length=100)
    # excerpt = models.CharField(max_length=200)
    content = models.TextField(max_length=2000)
    author = models.CharField(max_length=100, default='abcde')
    image = models.ImageField(upload_to="posts", null=True)
    date = models.DateField(default=timezone.now)
    # slug = models.SlugField(unique=True, db_index=True)
    
    # author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='posts')
    
    # tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user_name = models.CharField(max_length=100)
    user_email = models.EmailField()
    text = models.TextField(max_length=400)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

blog/forms.py
from django import forms

from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["post"]
        labels = {
            "user_name": "Your Name",
            "user_email": "Your Email",
            "text": "Your Comment"
        }
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = ['title','content','author','image','date']
        fields = ['image']
        

blog/views.py
from datetime import datetime
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from django.views import View

from .models import Post, Author 
from .forms import CommentForm, PostForm

# Create your views here.

def CreateBlogPost(request):
    author = Author.objects.all()
    if request.method == 'POST':
        title = request.POST.get('title')
        # image = request.POST.get('image')
        content = request.POST.get('content')
        author = request.POST.get('author')
        # date = datetime.today()
        form = PostForm(request.FILES)
        if form.is_valid():
            form.save()
    
            post = Post(
                title=title,
                # image=image,
                content=content,
                author=author,
                date=datetime.today(),
            )
            post.save()
            return redirect('blog:posts-page')
    return render(request, 'blog/create-post.html', {
        'author': author,
        'post_form': PostForm(),
    })

class StartingPageView(ListView):
    template_name = "blog/blog-home.html"
    model = Post
    ordering = ["-date"]
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        data = queryset[:3]
        return data
    
# def starting_page(request):
#     latest_posts = Post.objects.all().order_by('-date')[:3]
#     return render(request, 'blog/index.html', {
#         "posts": latest_posts
#     })

class AllPostsView(ListView):
    template_name = "blog/blog-all-posts.html"
    model = Post
    ordering = ["-date"]
    context_object_name = "all_posts"

# def posts(request):
#     all_posts = Post.objects.all().order_by('-date')
#     return render(request, 'blog/all-posts.html', {
#         "all_posts": all_posts
#     })

class SinglePostView(View):
    # def is_stored_post(self, request, post_id):
    #     stored_posts = request.session.get("stored_posts")
    #     if stored_posts is not None:
    #         is_saved_for_later = post_id in stored_posts
    #     else:
    #         is_saved_for_later = False

    #     return is_saved_for_later

    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        
        context = {
            "post": post,
            # "post_tags": post.tags.all(),
            "comment_form": CommentForm(),
            "comments": post.comments.all().order_by("-id"),
            # "saved_for_later": self.is_stored_post(request, post.id)
        }
        return render(request, "blog/blog-post.html", context)

    def post(self, request, pk):
        comment_form = CommentForm(request.POST)
        post = Post.objects.get(pk=pk)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse("post-detail-page", args=[pk]))
        
        context = {
            "post": post,
            # "post_tags": post.tags.all(),
            "comment_form": comment_form,
            "comments": post.comments.all().order_by("-id"),
            # "saved_for_later": self.is_stored_post(request, post.id)
        }
        return render(request, "blog/blog-post.html", context) 

# class ReadLaterView(View):
#     def get(self, request):
#         stored_posts = request.session.get("stored_posts")
#         context = {}

#         if stored_posts is None or len(stored_posts) == 0:
#             context["posts"] = []
#             context["has_posts"] = False
#         else:
#             posts = Post.objects.filter(id__in=stored_posts)
#             context["posts"] = posts
#             context["has_posts"] = True
        
#         return render(request, "blog/stored-posts.html", context)

#     def post(self, request):
#         stored_posts = request.session.get("stored_posts")

#         if stored_posts is None:
#             stored_posts = []

#         post_id = int(request.POST["post_id"])

#         if post_id not in stored_posts:
#             stored_posts.append(post_id)
#         else:
#             stored_posts.remove(post_id)

#         request.session["stored_posts"] = stored_posts

#         return redirect("blog:starting-page")


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["post_tags"] = self.object.tags.all()
    #     context["comment_form"] = CommentForm()
    #     return context
    

# def post_detail(request, slug):
#     identified_post = get_object_or_404(Post, slug=slug)
#     return render(request, 'blog/post-detail.html', {
#         "post": identified_post,
#         "post_tags": identified_post.tags.all()
#     })

blog/templates/blog/all-posts.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    All Posts
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/all-posts.css' %}">
{% endblock %}

{% block content %}
    <section id="all-posts">
        <h2>All Posts</h2>
        <ul>
            {% for post in all_posts %}
                {% include 'blog/include/post.html' %}
            {% endfor %}
        </ul>
    </section>

    {% include 'blog/footer.html' %}

{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon2.ico' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/app.css' %}">
    {% block css_files %}{% endblock %}
</head>
<body>
    <header id="main-navigation">
        <h1><a href="{% url 'index' %}" class="logo">Mental Wellness - Mind Matters</a></h1>
        <nav>
            {% comment %} <a href="{% url 'blog:read-later' %}">Stored Posts</a> {% endcomment %}
            <a href="{% url 'blog:posts-page' %}">All Posts</a>
        </nav>
    </header>
    {% block content %}{% endblock %}
</body>
</html>

blog/templates/blog/create-blog-post.html
{% extends 'blog/base.html' %}

{% block title %}
Create Post
{% endblock %}

{% block content %}
<div>
    <form action="{% url 'create-post' %}" method="POST">
    {% csrf_token %}
    <div class="form-left">
    <div class="form-group" "col-md-6">
      <label for="InputName">Blog Title</label>
      <input type="text" class="form-control" id="blog-title" name="title" aria-describedby="emailHelp" placeholder="Enter blog title" required>
    </div>
    <br>
    <div class="form-group" "col-md-6">
      <label for="InputEmail">Image</label>
      <input type="file" class="form-control" id="blog-image" name="image" aria-describedby="emailHelp" placeholder="select image" required>
    </div>
    <br>
    <div class="form-group">
      <label for="InputDOB">Blog Content</label>
      <input type="textarea" class="form-control" id="content" name="content" aria-describedby="emailHelp" placeholder="Enter blog content" required>
    </div> 
    <br>
    <div class="form-group">
      <label for="InputMobile">Author</label>
      <input type="text" class="form-control" id="author" name="author" aria-describedby="emailHelp" placeholder="Enter author name" required>
    </div><br>
    </div>
    <br>
  </div>
    {% comment %} <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div> {% endcomment %}
    <button type="submit" class="btn btn-primary" onclick="Validate()">Submit</button>
  </form>
</div>
  {% endblock %}

blog/templates/blog/create-post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'blog/images/favicon2.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/blog-home.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'blog/boxicons/css/boxicons.min.css' %}">
        <link href="{% static 'blog/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/all-posts.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/footer.css' %}">

        <style>
            .card:hover {
                transform:scale(1.1);
                box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
              }
        </style>
    </head>
    <body>
        <!-- Responsive navbar-->
        {% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
        </nav> {% endcomment %}

        <!-- ======= Top Bar ======= -->
        <div id="topbar" class="d-flex align-items-center fixed-top">
            <div class="container d-flex justify-content-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope"></i> <a href="mailto:mental.wellness.mind.matters@gmail.com">mental.wellness.mind.matters@gmail.com</a>
                <i class="bi bi-phone"></i> +91 9558955488
            </div>
            <div class="d-none d-lg-flex social-links align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
            </div>
        </div> <!-- End Topbar -->

        <!-- Header -->
        <header id="header" class="fixed-top">
            <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="{% url 'index' %}">Mental Wellness - Mind Matters</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                <li><a class="nav-link scrollto" href="{% url 'blog:starting-page' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'about-us' %}">About</a></li>
                <li><a class="nav-link scrollto" href="{% url 'blog:posts-page' %}">All Posts</a></li>
                </ul>
            </nav>
            <div>
        </header> <!-- End Header -->

        <!-- Page header with logo and tagline-->
            <header class="bg-light border-bottom mb-4">
                <div class="container">
                    <div class="text-center my-5">
                        {% comment %} <h1 class="fw-bolder">Welcome to Blog Home!</h1> {% endcomment %}
                        {% comment %} <p class="lead mb-0">A Bootstrap 5 starter layout for your next blog homepage</p> {% endcomment %}
                    </div>
                </div>
            </header>
    <main id="main">
        <!-- ======= Breadcrumbs Section ======= -->
        {% comment %} <section class="breadcrumbs">
            <div class="container">
    
            <div class="d-flex justify-content-between align-items-center">
                <h2>Registration</h2>
                <ol>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li>Registration</li>
                </ol>
            </div>
    
            </div>
        </section><!-- End Breadcrumbs Section -->
     {% endcomment %}
        <!-- Page content-->
        <section class="inner-page create-post" >
            <div class="container">
              <div>
              {% comment %} <div>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
              </div> {% endcomment %}
              <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-left">
                <div class="form-group">
                  <label for="InputName">Blog Title</label>
                  <input type="text" class="form-control" id="blog-title" name="title" aria-describedby="emailHelp" placeholder="Enter blog title" required>
                </div>
                <br>
                <div class="form-group">
                  {% comment %} <label for="InputEmail">Image</label> {% endcomment %}
                  {% comment %} <input type="file" class="form-control" id="blog-image" name="image" aria-describedby="emailHelp" placeholder="select image" required> {% endcomment %}
                  {{ post_form.as_p }}
                </div>
                <br>
                <div class="form-group">
                  <label for="InputDOB">Blog Content</label>
                  <input type="textarea" class="form-control" id="content" name="content" aria-describedby="emailHelp" placeholder="Enter blog content" required>
                </div> 
                <br>
                <div class="form-group">
                  <label for="InputMobile">Author</label>
                  <input type="text" class="form-control" id="author" name="author" aria-describedby="emailHelp" placeholder="Enter author name" required>
                  {% comment %} <select name="author" id="author" class="form-control" required>
                    <option value="" selected="False" style="display: none">Select Author </option> 
                    {% for i in author %}
                        <option value="{{ i.first_name }}">{{ i.first_name }} {{ i.last_name }}</option>
                    {% endfor %}
                  </select> {% endcomment %}
                </div><br>
                </div>
                <br>
              </div>
                {% comment %} <div class="form-group form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div> {% endcomment %}
                <button type="submit" class="btn btn-primary" onclick="Validate()">Submit</button>
              </form>
              <div>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
              </div>
            </div>
            </div>
            
          </section>
    </main>
            <!-- ======= Footer ======= -->
        <footer id="footer">

            <div class="footer-top">
            <div class="container">
                {% comment %} <div class="row">
        
                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>Medilab</h3>
                    <p>
                    A108 Adam Street <br>
                    New York, NY 535022<br>
                    United States <br><br>
                    <strong>Phone:</strong> +1 5589 55488 55<br>
                    <strong>Email:</strong> info@example.com<br>
                    </p>
                </div>
        
                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>
        
                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>
        
                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Join Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    <form action="" method="post">
                    <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>
        
                </div> 
            </div>
            </div>{% endcomment %}
        
            <div class="container d-md-flex py-4">
        
            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                &copy; Copyright <strong><span></span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/ -->
                {% comment %} Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> {% endcomment %}
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
            </div>
        </footer><!-- End Footer -->
            {% comment %} <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer> {% endcomment %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/blog-home.js' %}"></script>
    </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    Blog
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'blog/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/post.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block content %}
    <section id="welcome">
        <header>
            {% comment %} <img src="{% static 'blog/images/favicon2.ico' %}" alt=""> {% endcomment %}
            {% comment %} <h2><b>&nbsp;BLOG</b></h2> {% endcomment %}
        </header>
        {% comment %} <p>Hi, I am Drishti and I love to blog about tech and the world!</p> {% endcomment %}
    </section>

    <section id="latest-posts">
        <h2>Latest Posts</h2>
        <ul>
            {% for post in posts %}
                {% include 'blog/include/post.html' %}
            {% endfor %}
        </ul>
    </section>

    {% comment %} <section id="about">
        <h2>What We Do</h2>
        <p>
            I love programming, I love to help others and I enjoy exploring new technologies in general!
        </p>
        <p>
            My goal is to keep on growing as a developer - and if I could help you do the same, I'd be very happy!
        </p>
    </section> {% endcomment %}

  {% include 'blog/footer.html' %}

{% endblock %}

blog/templates/blog/post-detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block css_files %}
    {% comment %} <link rel="stylesheet" href="{% static 'blog/bootstrap.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'blog/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/post-detail.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/footer.css' %}">

{% endblock %}

{% block content %}

    {% if comment_form.errors %}
    <div id="alert">
        <h2>Saving the comment failed!</h2>
        <p>Please check the comment form below and fix your errors.</p>
        <a href="#comment-form">Fix!</a>
    </div>
    {% endif %}

    <section id="summary">
        <h2>{{ post.title }}</h2>
        <div>
            {% for tag in post_tags %}
                <span class="tag">{{ tag.caption }}</span>
            {% endfor %}
        </div>

        <div id="read-later">
            <form action="{% url 'blog:read-later' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{ post.id }}" name="post_id">
                <button>
                    {% if saved_for_later %}
                        Remove from "Read Later" List
                    {% else %}
                        Read later
                    {% endif %}
                </button>
            </form>
        </div>

        <article>
            <img src="{{ post.image.url }}" alt="{{ post.title }}">
            <address>By <a href="mailto:{{ post.author.email }}">{{ post.author }}</a></address>
            <div>
                Last updated on <time>{{ post.date|date:'d M Y' }}</time>
            </div>
        </article>
    </section>

    <main>
        <p>
           {{ post.content|linebreaks }}
        </p>
    </main>

    <section id="comments">
        <ul>
            {% for comment in comments %}
                <li>
                    <h2>{{ comment.user_name }}</h2>
                    <p>{{ comment.text|linebreaks }}</p>
                </li>
            {% endfor %}
        </ul>
    </section>

    <section id="comment-form">
        <h2>Your Comment</h2>
        <form action="{% url 'blog:post-detail-page' post.slug %}" method="POST">
            {% csrf_token %}
            {% for form_field in comment_form %}
                <div class="form-control {% if form_field.errors %}invalid{% endif %}">
                    {{ form_field.label_tag }}
                    {{ form_field }}
                    {{ form_field.errors }}
                </div>
            {% endfor %}
            <button>Save Comment</button>
        </form>
    </section>

    {% comment %} {% include 'blog/footer.html' %} {% endcomment %}

{% endblock %}

blog/templates/blog/stored-posts.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    Stored Posts
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'blog/css/stored-posts.css' %}">
{% endblock %}

{% block content %}
    <section id="stored-posts">
        {% if not has_posts %}
            <p>You didn't save any posts for later</p>
        {% endif %}
        <ul>
            {% for post in posts %}
                <li><a href={% url 'blog:post-detail-page' post.slug %}>{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}